spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5436/yourdb
    username: anwar
    password: anwar
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/